<?php

namespace Database\Seeders;

use App\Models\Province;
use Illuminate\Database\Seeder;

class ProvinceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $list = array(
            array(
                "id" => 101,
                "name" => "CHACHAPOYAS",
                "ubigeo" => 1,
                "department_id" => 1,
            ),
            array(
                "id" => 102,
                "name" => "BAGUA",
                "ubigeo" => 2,
                "department_id" => 1,
            ),
            array(
                "id" => 103,
                "name" => "BONGARA",
                "ubigeo" => 3,
                "department_id" => 1,
            ),
            array(
                "id" => 104,
                "name" => "LUYA",
                "ubigeo" => 4,
                "department_id" => 1,
            ),
            array(
                "id" => 105,
                "name" => "RODRIGUEZ DE MENDOZA",
                "ubigeo" => 5,
                "department_id" => 1,
            ),
            array(
                "id" => 106,
                "name" => "CONDORCANQUI",
                "ubigeo" => 6,
                "department_id" => 1,
            ),
            array(
                "id" => 107,
                "name" => "UTCUBAMBA",
                "ubigeo" => 7,
                "department_id" => 1,
            ),
            array(
                "id" => 201,
                "name" => "HUARAZ",
                "ubigeo" => 1,
                "department_id" => 2,
            ),
            array(
                "id" => 202,
                "name" => "AIJA",
                "ubigeo" => 2,
                "department_id" => 2,
            ),
            array(
                "id" => 203,
                "name" => "BOLOGNESI",
                "ubigeo" => 3,
                "department_id" => 2,
            ),
            array(
                "id" => 204,
                "name" => "CARHUAZ",
                "ubigeo" => 4,
                "department_id" => 2,
            ),
            array(
                "id" => 205,
                "name" => "CASMA",
                "ubigeo" => 5,
                "department_id" => 2,
            ),
            array(
                "id" => 206,
                "name" => "CORONGO",
                "ubigeo" => 6,
                "department_id" => 2,
            ),
            array(
                "id" => 207,
                "name" => "HUAYLAS",
                "ubigeo" => 7,
                "department_id" => 2,
            ),
            array(
                "id" => 208,
                "name" => "HUARI",
                "ubigeo" => 8,
                "department_id" => 2,
            ),
            array(
                "id" => 209,
                "name" => "MARISCAL LUZURIAGA",
                "ubigeo" => 9,
                "department_id" => 2,
            ),
            array(
                "id" => 210,
                "name" => "PALLASCA",
                "ubigeo" => 10,
                "department_id" => 2,
            ),
            array(
                "id" => 211,
                "name" => "POMABAMBA",
                "ubigeo" => 11,
                "department_id" => 2,
            ),
            array(
                "id" => 212,
                "name" => "RECUAY",
                "ubigeo" => 12,
                "department_id" => 2,
            ),
            array(
                "id" => 213,
                "name" => "SANTA",
                "ubigeo" => 13,
                "department_id" => 2,
            ),
            array(
                "id" => 214,
                "name" => "SIHUAS",
                "ubigeo" => 14,
                "department_id" => 2,
            ),
            array(
                "id" => 215,
                "name" => "YUNGAY",
                "ubigeo" => 15,
                "department_id" => 2,
            ),
            array(
                "id" => 216,
                "name" => "ANTONIO RAIMONDI",
                "ubigeo" => 16,
                "department_id" => 2,
            ),
            array(
                "id" => 217,
                "name" => "CARLOS FERMIN FITZCARRALD",
                "ubigeo" => 17,
                "department_id" => 2,
            ),
            array(
                "id" => 218,
                "name" => "ASUNCION",
                "ubigeo" => 18,
                "department_id" => 2,
            ),
            array(
                "id" => 219,
                "name" => "HUARMEY",
                "ubigeo" => 19,
                "department_id" => 2,
            ),
            array(
                "id" => 220,
                "name" => "OCROS",
                "ubigeo" => 20,
                "department_id" => 2,
            ),
            array(
                "id" => 301,
                "name" => "ABANCAY",
                "ubigeo" => 1,
                "department_id" => 3,
            ),
            array(
                "id" => 302,
                "name" => "AYMARAES",
                "ubigeo" => 2,
                "department_id" => 3,
            ),
            array(
                "id" => 303,
                "name" => "ANDAHUAYLAS",
                "ubigeo" => 3,
                "department_id" => 3,
            ),
            array(
                "id" => 304,
                "name" => "ANTABAMBA",
                "ubigeo" => 4,
                "department_id" => 3,
            ),
            array(
                "id" => 305,
                "name" => "COTABAMBAS",
                "ubigeo" => 5,
                "department_id" => 3,
            ),
            array(
                "id" => 306,
                "name" => "GRAU",
                "ubigeo" => 6,
                "department_id" => 3,
            ),
            array(
                "id" => 307,
                "name" => "CHINCHEROS",
                "ubigeo" => 7,
                "department_id" => 3,
            ),
            array(
                "id" => 401,
                "name" => "AREQUIPA",
                "ubigeo" => 1,
                "department_id" => 4,
            ),
            array(
                "id" => 402,
                "name" => "CAYLLOMA",
                "ubigeo" => 2,
                "department_id" => 4,
            ),
            array(
                "id" => 403,
                "name" => "CAMANA",
                "ubigeo" => 3,
                "department_id" => 4,
            ),
            array(
                "id" => 404,
                "name" => "CARAVELI",
                "ubigeo" => 4,
                "department_id" => 4,
            ),
            array(
                "id" => 405,
                "name" => "CASTILLA",
                "ubigeo" => 5,
                "department_id" => 4,
            ),
            array(
                "id" => 406,
                "name" => "CONDESUYOS",
                "ubigeo" => 6,
                "department_id" => 4,
            ),
            array(
                "id" => 407,
                "name" => "ISLAY",
                "ubigeo" => 7,
                "department_id" => 4,
            ),
            array(
                "id" => 408,
                "name" => "LA UNION",
                "ubigeo" => 8,
                "department_id" => 4,
            ),
            array(
                "id" => 501,
                "name" => "HUAMANGA",
                "ubigeo" => 1,
                "department_id" => 5,
            ),
            array(
                "id" => 502,
                "name" => "CANGALLO",
                "ubigeo" => 2,
                "department_id" => 5,
            ),
            array(
                "id" => 503,
                "name" => "HUANTA",
                "ubigeo" => 3,
                "department_id" => 5,
            ),
            array(
                "id" => 504,
                "name" => "LA MAR",
                "ubigeo" => 4,
                "department_id" => 5,
            ),
            array(
                "id" => 505,
                "name" => "LUCANAS",
                "ubigeo" => 5,
                "department_id" => 5,
            ),
            array(
                "id" => 506,
                "name" => "PARINACOCHAS",
                "ubigeo" => 6,
                "department_id" => 5,
            ),
            array(
                "id" => 507,
                "name" => "VICTOR FAJARDO",
                "ubigeo" => 7,
                "department_id" => 5,
            ),
            array(
                "id" => 508,
                "name" => "HUANCA SANCOS",
                "ubigeo" => 8,
                "department_id" => 5,
            ),
            array(
                "id" => 509,
                "name" => "VILCAS HUAMAN",
                "ubigeo" => 9,
                "department_id" => 5,
            ),
            array(
                "id" => 510,
                "name" => "PAUCAR DEL SARA SARA",
                "ubigeo" => 10,
                "department_id" => 5,
            ),
            array(
                "id" => 511,
                "name" => "SUCRE",
                "ubigeo" => 11,
                "department_id" => 5,
            ),
            array(
                "id" => 601,
                "name" => "CAJAMARCA",
                "ubigeo" => 1,
                "department_id" => 6,
            ),
            array(
                "id" => 602,
                "name" => "CAJABAMBA",
                "ubigeo" => 2,
                "department_id" => 6,
            ),
            array(
                "id" => 603,
                "name" => "CELENDIN",
                "ubigeo" => 3,
                "department_id" => 6,
            ),
            array(
                "id" => 604,
                "name" => "CONTUMAZA",
                "ubigeo" => 4,
                "department_id" => 6,
            ),
            array(
                "id" => 605,
                "name" => "CUTERVO",
                "ubigeo" => 5,
                "department_id" => 6,
            ),
            array(
                "id" => 606,
                "name" => "CHOTA",
                "ubigeo" => 6,
                "department_id" => 6,
            ),
            array(
                "id" => 607,
                "name" => "HUALGAYOC",
                "ubigeo" => 7,
                "department_id" => 6,
            ),
            array(
                "id" => 608,
                "name" => "JAEN",
                "ubigeo" => 8,
                "department_id" => 6,
            ),
            array(
                "id" => 609,
                "name" => "SANTA CRUZ",
                "ubigeo" => 9,
                "department_id" => 6,
            ),
            array(
                "id" => 610,
                "name" => "SAN MIGUEL",
                "ubigeo" => 10,
                "department_id" => 6,
            ),
            array(
                "id" => 611,
                "name" => "SAN IGNACIO",
                "ubigeo" => 11,
                "department_id" => 6,
            ),
            array(
                "id" => 612,
                "name" => "SAN MARCOS",
                "ubigeo" => 12,
                "department_id" => 6,
            ),
            array(
                "id" => 613,
                "name" => "SAN PABLO",
                "ubigeo" => 13,
                "department_id" => 6,
            ),
            array(
                "id" => 701,
                "name" => "CUSCO",
                "ubigeo" => 1,
                "department_id" => 7,
            ),
            array(
                "id" => 702,
                "name" => "ACOMAYO",
                "ubigeo" => 2,
                "department_id" => 7,
            ),
            array(
                "id" => 703,
                "name" => "ANTA",
                "ubigeo" => 3,
                "department_id" => 7,
            ),
            array(
                "id" => 704,
                "name" => "CALCA",
                "ubigeo" => 4,
                "department_id" => 7,
            ),
            array(
                "id" => 705,
                "name" => "CANAS",
                "ubigeo" => 5,
                "department_id" => 7,
            ),
            array(
                "id" => 706,
                "name" => "CANCHIS",
                "ubigeo" => 6,
                "department_id" => 7,
            ),
            array(
                "id" => 707,
                "name" => "CHUMBIVILCAS",
                "ubigeo" => 7,
                "department_id" => 7,
            ),
            array(
                "id" => 708,
                "name" => "ESPINAR",
                "ubigeo" => 8,
                "department_id" => 7,
            ),
            array(
                "id" => 709,
                "name" => "LA CONVENCION",
                "ubigeo" => 9,
                "department_id" => 7,
            ),
            array(
                "id" => 710,
                "name" => "PARURO",
                "ubigeo" => 10,
                "department_id" => 7,
            ),
            array(
                "id" => 711,
                "name" => "PAUCARTAMBO",
                "ubigeo" => 11,
                "department_id" => 7,
            ),
            array(
                "id" => 712,
                "name" => "QUISPICANCHI",
                "ubigeo" => 12,
                "department_id" => 7,
            ),
            array(
                "id" => 713,
                "name" => "URUBAMBA",
                "ubigeo" => 13,
                "department_id" => 7,
            ),
            array(
                "id" => 801,
                "name" => "HUANCAVELICA",
                "ubigeo" => 1,
                "department_id" => 8,
            ),
            array(
                "id" => 802,
                "name" => "ACOBAMBA",
                "ubigeo" => 2,
                "department_id" => 8,
            ),
            array(
                "id" => 803,
                "name" => "ANGARAES",
                "ubigeo" => 3,
                "department_id" => 8,
            ),
            array(
                "id" => 804,
                "name" => "CASTROVIRREYNA",
                "ubigeo" => 4,
                "department_id" => 8,
            ),
            array(
                "id" => 805,
                "name" => "TAYACAJA",
                "ubigeo" => 5,
                "department_id" => 8,
            ),
            array(
                "id" => 806,
                "name" => "HUAYTARA",
                "ubigeo" => 6,
                "department_id" => 8,
            ),
            array(
                "id" => 807,
                "name" => "CHURCAMPA",
                "ubigeo" => 7,
                "department_id" => 8,
            ),
            array(
                "id" => 901,
                "name" => "HUANUCO",
                "ubigeo" => 1,
                "department_id" => 9,
            ),
            array(
                "id" => 902,
                "name" => "AMBO",
                "ubigeo" => 2,
                "department_id" => 9,
            ),
            array(
                "id" => 903,
                "name" => "DOS DE MAYO",
                "ubigeo" => 3,
                "department_id" => 9,
            ),
            array(
                "id" => 904,
                "name" => "HUAMALIES",
                "ubigeo" => 4,
                "department_id" => 9,
            ),
            array(
                "id" => 905,
                "name" => "MARAÑON",
                "ubigeo" => 5,
                "department_id" => 9,
            ),
            array(
                "id" => 906,
                "name" => "LEONCIO PRADO",
                "ubigeo" => 6,
                "department_id" => 9,
            ),
            array(
                "id" => 907,
                "name" => "PACHITEA",
                "ubigeo" => 7,
                "department_id" => 9,
            ),
            array(
                "id" => 908,
                "name" => "PUERTO INCA",
                "ubigeo" => 8,
                "department_id" => 9,
            ),
            array(
                "id" => 909,
                "name" => "HUACAYBAMBA",
                "ubigeo" => 9,
                "department_id" => 9,
            ),
            array(
                "id" => 910,
                "name" => "LAURICOCHA",
                "ubigeo" => 10,
                "department_id" => 9,
            ),
            array(
                "id" => 911,
                "name" => "YAROWILCA",
                "ubigeo" => 11,
                "department_id" => 9,
            ),
            array(
                "id" => 1001,
                "name" => "ICA",
                "ubigeo" => 1,
                "department_id" => 10,
            ),
            array(
                "id" => 1002,
                "name" => "CHINCHA",
                "ubigeo" => 2,
                "department_id" => 10,
            ),
            array(
                "id" => 1003,
                "name" => "NAZCA",
                "ubigeo" => 3,
                "department_id" => 10,
            ),
            array(
                "id" => 1004,
                "name" => "PISCO",
                "ubigeo" => 4,
                "department_id" => 10,
            ),
            array(
                "id" => 1005,
                "name" => "PALPA",
                "ubigeo" => 5,
                "department_id" => 10,
            ),
            array(
                "id" => 1101,
                "name" => "HUANCAYO",
                "ubigeo" => 1,
                "department_id" => 11,
            ),
            array(
                "id" => 1102,
                "name" => "CONCEPCION",
                "ubigeo" => 2,
                "department_id" => 11,
            ),
            array(
                "id" => 1103,
                "name" => "JAUJA",
                "ubigeo" => 3,
                "department_id" => 11,
            ),
            array(
                "id" => 1104,
                "name" => "JUNIN",
                "ubigeo" => 4,
                "department_id" => 11,
            ),
            array(
                "id" => 1105,
                "name" => "TARMA",
                "ubigeo" => 5,
                "department_id" => 11,
            ),
            array(
                "id" => 1106,
                "name" => "YAULI",
                "ubigeo" => 6,
                "department_id" => 11,
            ),
            array(
                "id" => 1107,
                "name" => "SATIPO",
                "ubigeo" => 7,
                "department_id" => 11,
            ),
            array(
                "id" => 1108,
                "name" => "CHANCHAMAYO",
                "ubigeo" => 8,
                "department_id" => 11,
            ),
            array(
                "id" => 1109,
                "name" => "CHUPACA",
                "ubigeo" => 9,
                "department_id" => 11,
            ),
            array(
                "id" => 1201,
                "name" => "TRUJILLO",
                "ubigeo" => 1,
                "department_id" => 12,
            ),
            array(
                "id" => 1202,
                "name" => "BOLIVAR",
                "ubigeo" => 2,
                "department_id" => 12,
            ),
            array(
                "id" => 1203,
                "name" => "SANCHEZ CARRION",
                "ubigeo" => 3,
                "department_id" => 12,
            ),
            array(
                "id" => 1204,
                "name" => "OTUZCO",
                "ubigeo" => 4,
                "department_id" => 12,
            ),
            array(
                "id" => 1205,
                "name" => "PACASMAYO",
                "ubigeo" => 5,
                "department_id" => 12,
            ),
            array(
                "id" => 1206,
                "name" => "PATAZ",
                "ubigeo" => 6,
                "department_id" => 12,
            ),
            array(
                "id" => 1207,
                "name" => "SANTIAGO DE CHUCO",
                "ubigeo" => 7,
                "department_id" => 12,
            ),
            array(
                "id" => 1208,
                "name" => "ASCOPE",
                "ubigeo" => 8,
                "department_id" => 12,
            ),
            array(
                "id" => 1209,
                "name" => "CHEPEN",
                "ubigeo" => 9,
                "department_id" => 12,
            ),
            array(
                "id" => 1210,
                "name" => "JULCAN",
                "ubigeo" => 10,
                "department_id" => 12,
            ),
            array(
                "id" => 1211,
                "name" => "GRAN CHIMU",
                "ubigeo" => 11,
                "department_id" => 12,
            ),
            array(
                "id" => 1212,
                "name" => "VIRU",
                "ubigeo" => 12,
                "department_id" => 12,
            ),
            array(
                "id" => 1301,
                "name" => "CHICLAYO",
                "ubigeo" => 1,
                "department_id" => 13,
            ),
            array(
                "id" => 1302,
                "name" => "FERREÑAFE",
                "ubigeo" => 2,
                "department_id" => 13,
            ),
            array(
                "id" => 1303,
                "name" => "LAMBAYEQUE",
                "ubigeo" => 3,
                "department_id" => 13,
            ),
            array(
                "id" => 1401,
                "name" => "LIMA",
                "ubigeo" => 1,
                "department_id" => 14,
            ),
            array(
                "id" => 1402,
                "name" => "CAJATAMBO",
                "ubigeo" => 2,
                "department_id" => 14,
            ),
            array(
                "id" => 1403,
                "name" => "CANTA",
                "ubigeo" => 3,
                "department_id" => 14,
            ),
            array(
                "id" => 1404,
                "name" => "CAÑETE",
                "ubigeo" => 4,
                "department_id" => 14,
            ),
            array(
                "id" => 1405,
                "name" => "HUAURA",
                "ubigeo" => 5,
                "department_id" => 14,
            ),
            array(
                "id" => 1406,
                "name" => "HUAROCHIRI",
                "ubigeo" => 6,
                "department_id" => 14,
            ),
            array(
                "id" => 1407,
                "name" => "YAUYOS",
                "ubigeo" => 7,
                "department_id" => 14,
            ),
            array(
                "id" => 1408,
                "name" => "HUARAL",
                "ubigeo" => 8,
                "department_id" => 14,
            ),
            array(
                "id" => 1409,
                "name" => "BARRANCA",
                "ubigeo" => 9,
                "department_id" => 14,
            ),
            array(
                "id" => 1410,
                "name" => "OYON",
                "ubigeo" => 10,
                "department_id" => 14,
            ),
            array(
                "id" => 1501,
                "name" => "MAYNAS",
                "ubigeo" => 1,
                "department_id" => 15,
            ),
            array(
                "id" => 1502,
                "name" => "ALTO AMAZONAS",
                "ubigeo" => 2,
                "department_id" => 15,
            ),
            array(
                "id" => 1503,
                "name" => "LORETO",
                "ubigeo" => 3,
                "department_id" => 15,
            ),
            array(
                "id" => 1504,
                "name" => "REQUENA",
                "ubigeo" => 4,
                "department_id" => 15,
            ),
            array(
                "id" => 1505,
                "name" => "UCAYALI",
                "ubigeo" => 5,
                "department_id" => 15,
            ),
            array(
                "id" => 1506,
                "name" => "MARISCAL RAMON CASTILLA",
                "ubigeo" => 6,
                "department_id" => 15,
            ),
            array(
                "id" => 1507,
                "name" => "DATEM DEL MARAÑON",
                "ubigeo" => 7,
                "department_id" => 15,
            ),
            array(
                "id" => 1601,
                "name" => "TAMBOPATA",
                "ubigeo" => 1,
                "department_id" => 16,
            ),
            array(
                "id" => 1602,
                "name" => "MANU",
                "ubigeo" => 2,
                "department_id" => 16,
            ),
            array(
                "id" => 1603,
                "name" => "TAHUAMANU",
                "ubigeo" => 3,
                "department_id" => 16,
            ),
            array(
                "id" => 1701,
                "name" => "MARISCAL NIETO",
                "ubigeo" => 1,
                "department_id" => 17,
            ),
            array(
                "id" => 1702,
                "name" => "GENERAL SANCHEZ CERRO",
                "ubigeo" => 2,
                "department_id" => 17,
            ),
            array(
                "id" => 1703,
                "name" => "ILO",
                "ubigeo" => 3,
                "department_id" => 17,
            ),
            array(
                "id" => 1801,
                "name" => "PASCO",
                "ubigeo" => 1,
                "department_id" => 18,
            ),
            array(
                "id" => 1802,
                "name" => "DANIEL ALCIDES CARRION",
                "ubigeo" => 2,
                "department_id" => 18,
            ),
            array(
                "id" => 1803,
                "name" => "OXAPAMPA",
                "ubigeo" => 3,
                "department_id" => 18,
            ),
            array(
                "id" => 1901,
                "name" => "PIURA",
                "ubigeo" => 1,
                "department_id" => 19,
            ),
            array(
                "id" => 1902,
                "name" => "AYABACA",
                "ubigeo" => 2,
                "department_id" => 19,
            ),
            array(
                "id" => 1903,
                "name" => "HUANCABAMBA",
                "ubigeo" => 3,
                "department_id" => 19,
            ),
            array(
                "id" => 1904,
                "name" => "MORROPON",
                "ubigeo" => 4,
                "department_id" => 19,
            ),
            array(
                "id" => 1905,
                "name" => "PAITA",
                "ubigeo" => 5,
                "department_id" => 19,
            ),
            array(
                "id" => 1906,
                "name" => "SULLANA",
                "ubigeo" => 6,
                "department_id" => 19,
            ),
            array(
                "id" => 1907,
                "name" => "TALARA",
                "ubigeo" => 7,
                "department_id" => 19,
            ),
            array(
                "id" => 1908,
                "name" => "SECHURA",
                "ubigeo" => 8,
                "department_id" => 19,
            ),
            array(
                "id" => 2001,
                "name" => "PUNO",
                "ubigeo" => 1,
                "department_id" => 20,
            ),
            array(
                "id" => 2002,
                "name" => "AZANGARO",
                "ubigeo" => 2,
                "department_id" => 20,
            ),
            array(
                "id" => 2003,
                "name" => "CARABAYA",
                "ubigeo" => 3,
                "department_id" => 20,
            ),
            array(
                "id" => 2004,
                "name" => "CHUCUITO",
                "ubigeo" => 4,
                "department_id" => 20,
            ),
            array(
                "id" => 2005,
                "name" => "HUANCANE",
                "ubigeo" => 5,
                "department_id" => 20,
            ),
            array(
                "id" => 2006,
                "name" => "LAMPA",
                "ubigeo" => 6,
                "department_id" => 20,
            ),
            array(
                "id" => 2007,
                "name" => "MELGAR",
                "ubigeo" => 7,
                "department_id" => 20,
            ),
            array(
                "id" => 2008,
                "name" => "SANDIA",
                "ubigeo" => 8,
                "department_id" => 20,
            ),
            array(
                "id" => 2009,
                "name" => "SAN ROMAN",
                "ubigeo" => 9,
                "department_id" => 20,
            ),
            array(
                "id" => 2010,
                "name" => "YUNGUYO",
                "ubigeo" => 10,
                "department_id" => 20,
            ),
            array(
                "id" => 2011,
                "name" => "SAN ANTONIO DE PUTINA",
                "ubigeo" => 11,
                "department_id" => 20,
            ),
            array(
                "id" => 2012,
                "name" => "EL COLLAO",
                "ubigeo" => 12,
                "department_id" => 20,
            ),
            array(
                "id" => 2013,
                "name" => "MOHO",
                "ubigeo" => 13,
                "department_id" => 20,
            ),
            array(
                "id" => 2101,
                "name" => "MOYOBAMBA",
                "ubigeo" => 1,
                "department_id" => 21,
            ),
            array(
                "id" => 2102,
                "name" => "HUALLAGA",
                "ubigeo" => 2,
                "department_id" => 21,
            ),
            array(
                "id" => 2103,
                "name" => "LAMAS",
                "ubigeo" => 3,
                "department_id" => 21,
            ),
            array(
                "id" => 2104,
                "name" => "MARISCAL CACERES",
                "ubigeo" => 4,
                "department_id" => 21,
            ),
            array(
                "id" => 2105,
                "name" => "RIOJA",
                "ubigeo" => 5,
                "department_id" => 21,
            ),
            array(
                "id" => 2106,
                "name" => "SAN MARTIN",
                "ubigeo" => 6,
                "department_id" => 21,
            ),
            array(
                "id" => 2107,
                "name" => "BELLAVISTA",
                "ubigeo" => 7,
                "department_id" => 21,
            ),
            array(
                "id" => 2108,
                "name" => "TOCACHE",
                "ubigeo" => 8,
                "department_id" => 21,
            ),
            array(
                "id" => 2109,
                "name" => "PICOTA",
                "ubigeo" => 9,
                "department_id" => 21,
            ),
            array(
                "id" => 2110,
                "name" => "EL DORADO",
                "ubigeo" => 10,
                "department_id" => 21,
            ),
            array(
                "id" => 2201,
                "name" => "TACNA",
                "ubigeo" => 1,
                "department_id" => 22,
            ),
            array(
                "id" => 2202,
                "name" => "TARATA",
                "ubigeo" => 2,
                "department_id" => 22,
            ),
            array(
                "id" => 2203,
                "name" => "JORGE BASADRE",
                "ubigeo" => 3,
                "department_id" => 22,
            ),
            array(
                "id" => 2204,
                "name" => "CANDARAVE",
                "ubigeo" => 4,
                "department_id" => 22,
            ),
            array(
                "id" => 2301,
                "name" => "TUMBES",
                "ubigeo" => 1,
                "department_id" => 23,
            ),
            array(
                "id" => 2302,
                "name" => "CONTRALMIRANTE VILLAR",
                "ubigeo" => 2,
                "department_id" => 23,
            ),
            array(
                "id" => 2303,
                "name" => "ZARUMILLA",
                "ubigeo" => 3,
                "department_id" => 23,
            ),
            array(
                "id" => 2401,
                "name" => "CALLAO",
                "ubigeo" => 1,
                "department_id" => 24,
            ),
            array(
                "id" => 2501,
                "name" => "CORONEL PORTILLO",
                "ubigeo" => 1,
                "department_id" => 25,
            ),
            array(
                "id" => 2502,
                "name" => "PADRE ABAD",
                "ubigeo" => 2,
                "department_id" => 25,
            ),
            array(
                "id" => 2503,
                "name" => "ATALAYA",
                "ubigeo" => 3,
                "department_id" => 25,
            ),
            array(
                "id" => 2504,
                "name" => "PURUS",
                "ubigeo" => 4,
                "department_id" => 25,
            ),
            array(
                "id" => 9101,
                "name" => "ARGELIA",
                "ubigeo" => 1,
                "department_id" => 91,
            ),
            array(
                "id" => 9102,
                "name" => "COSTA DE MARFIL",
                "ubigeo" => 2,
                "department_id" => 91,
            ),
            array(
                "id" => 9103,
                "name" => "EGIPTO, REPUBLICA ARABE",
                "ubigeo" => 3,
                "department_id" => 91,
            ),
            array(
                "id" => 9104,
                "name" => "KENIA",
                "ubigeo" => 4,
                "department_id" => 91,
            ),
            array(
                "id" => 9105,
                "name" => "MARRUECOS",
                "ubigeo" => 5,
                "department_id" => 91,
            ),
            array(
                "id" => 9106,
                "name" => "SUDAFRICA",
                "ubigeo" => 6,
                "department_id" => 91,
            ),
            array(
                "id" => 9107,
                "name" => "ZAMBIA",
                "ubigeo" => 7,
                "department_id" => 91,
            ),
            array(
                "id" => 9108,
                "name" => "ZIMBABWE",
                "ubigeo" => 8,
                "department_id" => 91,
            ),
            array(
                "id" => 9109,
                "name" => "TUNEZ",
                "ubigeo" => 9,
                "department_id" => 91,
            ),
            array(
                "id" => 9110,
                "name" => "SOMALIA",
                "ubigeo" => 10,
                "department_id" => 91,
            ),
            array(
                "id" => 9111,
                "name" => "NIGERIA",
                "ubigeo" => 11,
                "department_id" => 91,
            ),
            array(
                "id" => 9112,
                "name" => "GHANA",
                "ubigeo" => 12,
                "department_id" => 91,
            ),
            array(
                "id" => 9113,
                "name" => "ANGOLA",
                "ubigeo" => 13,
                "department_id" => 91,
            ),
            array(
                "id" => 9114,
                "name" => "BURKINA FASO",
                "ubigeo" => 14,
                "department_id" => 91,
            ),
            array(
                "id" => 9115,
                "name" => "ZAIRE",
                "ubigeo" => 15,
                "department_id" => 91,
            ),
            array(
                "id" => 9116,
                "name" => "LIBIA",
                "ubigeo" => 16,
                "department_id" => 91,
            ),
            array(
                "id" => 9117,
                "name" => "MOZAMBIQUE",
                "ubigeo" => 17,
                "department_id" => 91,
            ),
            array(
                "id" => 9118,
                "name" => "SWAZILANDIA",
                "ubigeo" => 18,
                "department_id" => 91,
            ),
            array(
                "id" => 9119,
                "name" => "MADAGASCAR",
                "ubigeo" => 19,
                "department_id" => 91,
            ),
            array(
                "id" => 9120,
                "name" => "ETIOPIA",
                "ubigeo" => 20,
                "department_id" => 91,
            ),
            array(
                "id" => 9121,
                "name" => "SENEGAL",
                "ubigeo" => 21,
                "department_id" => 91,
            ),
            array(
                "id" => 9122,
                "name" => "GUINEA ECUATORIAL",
                "ubigeo" => 22,
                "department_id" => 91,
            ),
            array(
                "id" => 9123,
                "name" => "CAMERUN",
                "ubigeo" => 23,
                "department_id" => 91,
            ),
            array(
                "id" => 9124,
                "name" => "REP. DEMOCRATICA DEL CONGO",
                "ubigeo" => 24,
                "department_id" => 91,
            ),
            array(
                "id" => 9126,
                "name" => "REPUBLICA UNIDA DE TANZANIA",
                "ubigeo" => 26,
                "department_id" => 91,
            ),
            array(
                "id" => 9127,
                "name" => "REPUBLICA DE GUINEA",
                "ubigeo" => 27,
                "department_id" => 91,
            ),
            array(
                "id" => 9128,
                "name" => "SUDAN",
                "ubigeo" => 28,
                "department_id" => 91,
            ),
            array(
                "id" => 9129,
                "name" => "MAURICIO",
                "ubigeo" => 29,
                "department_id" => 91,
            ),
            array(
                "id" => 9130,
                "name" => "BOTSUANA",
                "ubigeo" => 30,
                "department_id" => 91,
            ),
            array(
                "id" => 9131,
                "name" => "GABON",
                "ubigeo" => 31,
                "department_id" => 91,
            ),
            array(
                "id" => 9134,
                "name" => "REPUBLICA DE GAMBIA",
                "ubigeo" => 34,
                "department_id" => 91,
            ),
            array(
                "id" => 9201,
                "name" => "ANTILLAS HOLANDESAS",
                "ubigeo" => 1,
                "department_id" => 92,
            ),
            array(
                "id" => 9202,
                "name" => "ARGENTINA",
                "ubigeo" => 2,
                "department_id" => 92,
            ),
            array(
                "id" => 9203,
                "name" => "BAHAMAS, ISLAS",
                "ubigeo" => 3,
                "department_id" => 92,
            ),
            array(
                "id" => 9204,
                "name" => "BOLIVIA",
                "ubigeo" => 4,
                "department_id" => 92,
            ),
            array(
                "id" => 9205,
                "name" => "BRASIL",
                "ubigeo" => 5,
                "department_id" => 92,
            ),
            array(
                "id" => 9206,
                "name" => "CANADA",
                "ubigeo" => 6,
                "department_id" => 92,
            ),
            array(
                "id" => 9207,
                "name" => "COLOMBIA",
                "ubigeo" => 7,
                "department_id" => 92,
            ),
            array(
                "id" => 9208,
                "name" => "COSTA RICA",
                "ubigeo" => 8,
                "department_id" => 92,
            ),
            array(
                "id" => 9209,
                "name" => "CUBA",
                "ubigeo" => 9,
                "department_id" => 92,
            ),
            array(
                "id" => 9210,
                "name" => "CHILE",
                "ubigeo" => 10,
                "department_id" => 92,
            ),
            array(
                "id" => 9211,
                "name" => "ECUADOR",
                "ubigeo" => 11,
                "department_id" => 92,
            ),
            array(
                "id" => 9212,
                "name" => "EL SALVADOR",
                "ubigeo" => 12,
                "department_id" => 92,
            ),
            array(
                "id" => 9213,
                "name" => "ESTADOS UNIDOS DE AMERICA",
                "ubigeo" => 13,
                "department_id" => 92,
            ),
            array(
                "id" => 9215,
                "name" => "GUATEMALA",
                "ubigeo" => 15,
                "department_id" => 92,
            ),
            array(
                "id" => 9216,
                "name" => "HAITI",
                "ubigeo" => 16,
                "department_id" => 92,
            ),
            array(
                "id" => 9217,
                "name" => "HONDURAS",
                "ubigeo" => 17,
                "department_id" => 92,
            ),
            array(
                "id" => 9218,
                "name" => "JAMAICA",
                "ubigeo" => 18,
                "department_id" => 92,
            ),
            array(
                "id" => 9219,
                "name" => "MEXICO",
                "ubigeo" => 19,
                "department_id" => 92,
            ),
            array(
                "id" => 9220,
                "name" => "NICARAGUA",
                "ubigeo" => 20,
                "department_id" => 92,
            ),
            array(
                "id" => 9221,
                "name" => "PANAMA",
                "ubigeo" => 21,
                "department_id" => 92,
            ),
            array(
                "id" => 9222,
                "name" => "PARAGUAY",
                "ubigeo" => 22,
                "department_id" => 92,
            ),
            array(
                "id" => 9223,
                "name" => "PUERTO RICO",
                "ubigeo" => 23,
                "department_id" => 92,
            ),
            array(
                "id" => 9224,
                "name" => "REPUBLICA DOMINICANA",
                "ubigeo" => 24,
                "department_id" => 92,
            ),
            array(
                "id" => 9225,
                "name" => "SURINAM",
                "ubigeo" => 25,
                "department_id" => 92,
            ),
            array(
                "id" => 9226,
                "name" => "TRINIDAD TOBAGO",
                "ubigeo" => 26,
                "department_id" => 92,
            ),
            array(
                "id" => 9227,
                "name" => "URUGUAY",
                "ubigeo" => 27,
                "department_id" => 92,
            ),
            array(
                "id" => 9228,
                "name" => "VENEZUELA",
                "ubigeo" => 28,
                "department_id" => 92,
            ),
            array(
                "id" => 9229,
                "name" => "BARBADOS",
                "ubigeo" => 29,
                "department_id" => 92,
            ),
            array(
                "id" => 9230,
                "name" => "GUAYANA FRANCESA",
                "ubigeo" => 30,
                "department_id" => 92,
            ),
            array(
                "id" => 9232,
                "name" => "BELICE",
                "ubigeo" => 32,
                "department_id" => 92,
            ),
            array(
                "id" => 9235,
                "name" => "SANTA LUCIA",
                "ubigeo" => 35,
                "department_id" => 92,
            ),
            array(
                "id" => 9236,
                "name" => "ISLAS CAIMAN",
                "ubigeo" => 36,
                "department_id" => 92,
            ),
            array(
                "id" => 9301,
                "name" => "COREA DEL SUR, REPUBLICA DE",
                "ubigeo" => 1,
                "department_id" => 93,
            ),
            array(
                "id" => 9302,
                "name" => "CHINA, REPUBLICA POPULAR",
                "ubigeo" => 2,
                "department_id" => 93,
            ),
            array(
                "id" => 9304,
                "name" => "INDIA",
                "ubigeo" => 4,
                "department_id" => 93,
            ),
            array(
                "id" => 9305,
                "name" => "IRAK",
                "ubigeo" => 5,
                "department_id" => 93,
            ),
            array(
                "id" => 9306,
                "name" => "ISRAEL",
                "ubigeo" => 6,
                "department_id" => 93,
            ),
            array(
                "id" => 9307,
                "name" => "JAPON",
                "ubigeo" => 7,
                "department_id" => 93,
            ),
            array(
                "id" => 9308,
                "name" => "LIBANO",
                "ubigeo" => 8,
                "department_id" => 93,
            ),
            array(
                "id" => 9309,
                "name" => "SRI LANKA",
                "ubigeo" => 9,
                "department_id" => 93,
            ),
            array(
                "id" => 9310,
                "name" => "TAILANDIA",
                "ubigeo" => 10,
                "department_id" => 93,
            ),
            array(
                "id" => 9311,
                "name" => "INDONESIA",
                "ubigeo" => 11,
                "department_id" => 93,
            ),
            array(
                "id" => 9312,
                "name" => "SIRIA",
                "ubigeo" => 12,
                "department_id" => 93,
            ),
            array(
                "id" => 9313,
                "name" => "JORDANIA",
                "ubigeo" => 13,
                "department_id" => 93,
            ),
            array(
                "id" => 9314,
                "name" => "PALESTINA",
                "ubigeo" => 14,
                "department_id" => 93,
            ),
            array(
                "id" => 9315,
                "name" => "TURQUIA",
                "ubigeo" => 15,
                "department_id" => 93,
            ),
            array(
                "id" => 9316,
                "name" => "COREA DEL NORTE",
                "ubigeo" => 16,
                "department_id" => 93,
            ),
            array(
                "id" => 9317,
                "name" => "MONGOLIA",
                "ubigeo" => 17,
                "department_id" => 93,
            ),
            array(
                "id" => 9318,
                "name" => "PAKISTAN",
                "ubigeo" => 18,
                "department_id" => 93,
            ),
            array(
                "id" => 9319,
                "name" => "ARABIA SAUDITA",
                "ubigeo" => 19,
                "department_id" => 93,
            ),
            array(
                "id" => 9320,
                "name" => "VIETNAN",
                "ubigeo" => 20,
                "department_id" => 93,
            ),
            array(
                "id" => 9321,
                "name" => "KAZAJSTAN",
                "ubigeo" => 21,
                "department_id" => 93,
            ),
            array(
                "id" => 9322,
                "name" => "YEMEN",
                "ubigeo" => 22,
                "department_id" => 93,
            ),
            array(
                "id" => 9323,
                "name" => "TAIWAN",
                "ubigeo" => 23,
                "department_id" => 93,
            ),
            array(
                "id" => 9324,
                "name" => "IRAN",
                "ubigeo" => 24,
                "department_id" => 93,
            ),
            array(
                "id" => 9325,
                "name" => "SINGAPUR",
                "ubigeo" => 25,
                "department_id" => 93,
            ),
            array(
                "id" => 9326,
                "name" => "KIRGUISTAN",
                "ubigeo" => 26,
                "department_id" => 93,
            ),
            array(
                "id" => 9327,
                "name" => "AFGANISTAN",
                "ubigeo" => 27,
                "department_id" => 93,
            ),
            array(
                "id" => 9328,
                "name" => "KUWAIT",
                "ubigeo" => 28,
                "department_id" => 93,
            ),
            array(
                "id" => 9329,
                "name" => "TURKMENISTAN",
                "ubigeo" => 29,
                "department_id" => 93,
            ),
            array(
                "id" => 9330,
                "name" => "MALASIA",
                "ubigeo" => 30,
                "department_id" => 93,
            ),
            array(
                "id" => 9331,
                "name" => "GEORGIA",
                "ubigeo" => 31,
                "department_id" => 93,
            ),
            array(
                "id" => 9332,
                "name" => "FILIPINAS",
                "ubigeo" => 32,
                "department_id" => 93,
            ),
            array(
                "id" => 9335,
                "name" => "AZERBAIYAN",
                "ubigeo" => 35,
                "department_id" => 93,
            ),
            array(
                "id" => 9337,
                "name" => "EMIRATOS ARABES UNIDOS",
                "ubigeo" => 37,
                "department_id" => 93,
            ),
            array(
                "id" => 9338,
                "name" => "QATAR",
                "ubigeo" => 38,
                "department_id" => 93,
            ),
            array(
                "id" => 9339,
                "name" => "OMAN",
                "ubigeo" => 39,
                "department_id" => 93,
            ),
            array(
                "id" => 9341,
                "name" => "BAREIN",
                "ubigeo" => 41,
                "department_id" => 93,
            ),
            array(
                "id" => 9343,
                "name" => "UZBEKISTAN",
                "ubigeo" => 43,
                "department_id" => 93,
            ),
            array(
                "id" => 9345,
                "name" => "BRUNEI",
                "ubigeo" => 45,
                "department_id" => 93,
            ),
            array(
                "id" => 9402,
                "name" => "ALEMANIA",
                "ubigeo" => 2,
                "department_id" => 94,
            ),
            array(
                "id" => 9403,
                "name" => "AUSTRIA",
                "ubigeo" => 3,
                "department_id" => 94,
            ),
            array(
                "id" => 9404,
                "name" => "BELGICA",
                "ubigeo" => 4,
                "department_id" => 94,
            ),
            array(
                "id" => 9405,
                "name" => "BULGARIA",
                "ubigeo" => 5,
                "department_id" => 94,
            ),
            array(
                "id" => 9406,
                "name" => "REPUBLICA CHECA",
                "ubigeo" => 6,
                "department_id" => 94,
            ),
            array(
                "id" => 9407,
                "name" => "CHIPRE",
                "ubigeo" => 7,
                "department_id" => 94,
            ),
            array(
                "id" => 9408,
                "name" => "DINAMARCA",
                "ubigeo" => 8,
                "department_id" => 94,
            ),
            array(
                "id" => 9409,
                "name" => "ESPAÑA",
                "ubigeo" => 9,
                "department_id" => 94,
            ),
            array(
                "id" => 9410,
                "name" => "FINLANDIA",
                "ubigeo" => 10,
                "department_id" => 94,
            ),
            array(
                "id" => 9411,
                "name" => "FRANCIA",
                "ubigeo" => 11,
                "department_id" => 94,
            ),
            array(
                "id" => 9412,
                "name" => "GRAN BRETAÑA",
                "ubigeo" => 12,
                "department_id" => 94,
            ),
            array(
                "id" => 9413,
                "name" => "GRECIA",
                "ubigeo" => 13,
                "department_id" => 94,
            ),
            array(
                "id" => 9414,
                "name" => "HOLANDA",
                "ubigeo" => 14,
                "department_id" => 94,
            ),
            array(
                "id" => 9415,
                "name" => "HUNGRIA",
                "ubigeo" => 15,
                "department_id" => 94,
            ),
            array(
                "id" => 9416,
                "name" => "ISLANDIA",
                "ubigeo" => 16,
                "department_id" => 94,
            ),
            array(
                "id" => 9417,
                "name" => "ITALIA",
                "ubigeo" => 17,
                "department_id" => 94,
            ),
            array(
                "id" => 9418,
                "name" => "IRLANDA",
                "ubigeo" => 18,
                "department_id" => 94,
            ),
            array(
                "id" => 9419,
                "name" => "LIECHTENSTEIN, PRINCIPADO DE",
                "ubigeo" => 19,
                "department_id" => 94,
            ),
            array(
                "id" => 9420,
                "name" => "LUXEMBURGO, GRAN DUCADO DE",
                "ubigeo" => 20,
                "department_id" => 94,
            ),
            array(
                "id" => 9421,
                "name" => "MALTA",
                "ubigeo" => 21,
                "department_id" => 94,
            ),
            array(
                "id" => 9422,
                "name" => "MONACO, PRINCIPADO DE",
                "ubigeo" => 22,
                "department_id" => 94,
            ),
            array(
                "id" => 9423,
                "name" => "NORUEGA",
                "ubigeo" => 23,
                "department_id" => 94,
            ),
            array(
                "id" => 9424,
                "name" => "POLONIA",
                "ubigeo" => 24,
                "department_id" => 94,
            ),
            array(
                "id" => 9425,
                "name" => "PORTUGAL",
                "ubigeo" => 25,
                "department_id" => 94,
            ),
            array(
                "id" => 9426,
                "name" => "RUMANIA",
                "ubigeo" => 26,
                "department_id" => 94,
            ),
            array(
                "id" => 9427,
                "name" => "SUECIA",
                "ubigeo" => 27,
                "department_id" => 94,
            ),
            array(
                "id" => 9428,
                "name" => "SUIZA",
                "ubigeo" => 28,
                "department_id" => 94,
            ),
            array(
                "id" => 9429,
                "name" => "RUSIA",
                "ubigeo" => 29,
                "department_id" => 94,
            ),
            array(
                "id" => 9430,
                "name" => "YUGOSLAVIA",
                "ubigeo" => 30,
                "department_id" => 94,
            ),
            array(
                "id" => 9431,
                "name" => "CROACIA",
                "ubigeo" => 31,
                "department_id" => 94,
            ),
            array(
                "id" => 9432,
                "name" => "MOLDAVIA",
                "ubigeo" => 32,
                "department_id" => 94,
            ),
            array(
                "id" => 9433,
                "name" => "ESLOVENIA",
                "ubigeo" => 33,
                "department_id" => 94,
            ),
            array(
                "id" => 9434,
                "name" => "UCRANIA",
                "ubigeo" => 34,
                "department_id" => 94,
            ),
            array(
                "id" => 9435,
                "name" => "UZBEKISTAN",
                "ubigeo" => 35,
                "department_id" => 94,
            ),
            array(
                "id" => 9436,
                "name" => "BIELORRUSIA",
                "ubigeo" => 36,
                "department_id" => 94,
            ),
            array(
                "id" => 9437,
                "name" => "MACEDONIA",
                "ubigeo" => 37,
                "department_id" => 94,
            ),
            array(
                "id" => 9438,
                "name" => "ESLOVAQUIA",
                "ubigeo" => 38,
                "department_id" => 94,
            ),
            array(
                "id" => 9439,
                "name" => "LETONIA",
                "ubigeo" => 39,
                "department_id" => 94,
            ),
            array(
                "id" => 9440,
                "name" => "LITUANIA",
                "ubigeo" => 40,
                "department_id" => 94,
            ),
            array(
                "id" => 9441,
                "name" => "IRLANDA DEL NORTE",
                "ubigeo" => 41,
                "department_id" => 94,
            ),
            array(
                "id" => 9442,
                "name" => "ANDORRA, PRINCIPADO DE",
                "ubigeo" => 42,
                "department_id" => 94,
            ),
            array(
                "id" => 9443,
                "name" => "ALBANIA",
                "ubigeo" => 43,
                "department_id" => 94,
            ),
            array(
                "id" => 9444,
                "name" => "ESTONIA",
                "ubigeo" => 44,
                "department_id" => 94,
            ),
            array(
                "id" => 9447,
                "name" => "SAN MARINO, REPUBLICA DE",
                "ubigeo" => 47,
                "department_id" => 94,
            ),
            array(
                "id" => 9448,
                "name" => "SERBIA",
                "ubigeo" => 48,
                "department_id" => 94,
            ),
            array(
                "id" => 9501,
                "name" => "AUSTRALIA",
                "ubigeo" => 1,
                "department_id" => 95,
            ),
            array(
                "id" => 9502,
                "name" => "NUEVA ZELANDA",
                "ubigeo" => 2,
                "department_id" => 95,
            ),
            array(
                "id" => 9503,
                "name" => "PAPUA NUEVA GUINEA",
                "ubigeo" => 3,
                "department_id" => 95,
            ),
            array(
                "id" => 9504,
                "name" => "SAMOA AMERICANA",
                "ubigeo" => 4,
                "department_id" => 95,
            ),
            array(
                "id" => 9505,
                "name" => "PALAU",
                "ubigeo" => 5,
                "department_id" => 95,
            ),
        );

        foreach ($list as $province) {
            Province::create($province);
        }
    }
}
